# This workflow will install Python dependencies, load the dataset, and run the training script on CI with cache to dataset.

name: Python application

on:
  push:

permissions:
  contents: read

env:
  DATASET_CACHE_DIR: dataset_cache

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/*requirements.txt') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          pwd
          python -m venv venv
          . venv/bin/activate
          python -m pip install protobuf==3.19.6
          ls venv/lib/python3.10/site-packages
          echo "-----"
          ls venv/lib64/python3.10/site-packages
          touch venv/lib64/python3.10/site-packages/google/__init__.py
          touch venv/lib/python3.10/site-packages/google/__init__.py       
          touch venv/lib64/python3.10/site-packages/google/protobuf/internal/builder.py
          touch venv/lib/python3.10/site-packages/google/protobuf/internal/builder.py
          cp builder.py venv/lib/python3.10/site-packages/google/protobuf/internal/builder.py
          cp builder.py venv/lib64/python3.10/site-packages/google/protobuf/internal/builder.py
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

  load_dataset:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Restore cached pip packages
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Activate venv
        run: source venv/bin/activate

      - name: Cache dataset
        uses: actions/cache@v2
        with:
          path: ${{ env.DATASET_CACHE_DIR }}
          key: dataset-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            dataset-${{ hashFiles('requirements.txt') }}
      - name: Load dataset
        run: |
          if [ ! -d "$env:DATASET_CACHE_DIR" ]; then
            mkdir "$env:DATASET_CACHE_DIR"
            ls venv/lib/python3.10/site-packages
            pwd
            python -m dataset.data
          fi
#  train:
#    runs-on: ubuntu-latest
#    needs: load_dataset
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Python 3.10
#        uses: actions/setup-python@v3
#        with:
#          python-version: "3.10"
#      - name: Run Train
#        run: |
#          python train.py
#  artifacts:
#    runs-on: ubuntu-latest
#    needs: train
#    steps:
#      - uses: actions/checkout@v3
#      - name: 'Upload Artifact'
#        uses: actions/upload-artifact@v3
#        with:
#          name: my-artifact
#          path: models/1/model.ckpt
#          retention-days: 5