# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  DATASET_CACHE_DIR: ${{ runner.workspace }}/dataset_cache

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Cache dataset
      uses: actions/cache@v2
      with:
        path: ${{ env.DATASET_CACHE_DIR }}
        key: dataset-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          dataset-${{ hashFiles('requirements.txt') }}

    - name: Load dataset
      run: |
        if [ ! -d "$env:DATASET_CACHE_DIR" ]; then
          mkdir "$env:DATASET_CACHE_DIR"
          python data.py
        fi

    - uses: actions/checkout@v3
        - name: Set up Python 3.10
        uses: actions/setup-python@v3

      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install  --upgrade pip
        pip uninstall protobuf
        pip uninstall google
        pip install protobuf==3.19.6
        touch /opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/google/__init__.py
        touch /opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/google/protobuf/internal/builder.py
        cp builder.py /opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/google/protobuf/internal/builder.py
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Train
      run: |
        python train.py

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: models/1/model.ckpt
        retention-days: 5
